#!/bin/bash
BUILDPATH="${1:-empty}"
SRCPATH="${2:-empty}"
INSTALLBENCHMARKPATH="${3:-empty}"
INSTALLTESTPATH="${4:-empty}"
COMPILERCFLAG="${5:-empty}"
COMPILERCXXFLAG="${6:-empty}"
COMPILERADDITIONALFLAG="${7:-empty}"
PLATFORMCFLAG="${8:-empty}"
$COMPC $COMPCXX $COMPADD $PLATFORM
[ $# -eq 0 ] && exit 1


cd $BUILDPATH || exit
cmake $INSTALLBENCHMARKPATH $INSTALLTESTPATH $COMPILERCFLAG $COMPILERCXXFLAG $COMPILERADDITIONALFLAG $PLATFORMCFLAG $SRCPATH
make -j
make test
make install
